### ISSUE TITLE
Variables do not work correctly inside MD files

### ISSUE THREAD

**Issue by bigbrownies** [orca-scan/express-md#2]
Hi,

Problem : the variables works only in template. Docs say that should be work on markdown files too.

i try to get the markdown variable works.
I have an index.md, a template.html.

My options are this :
exports.mdRouter = expressMd({
  dir: path.join(process.cwd(), 'src', 'docs'),
  url: '/',
  vars: {
    url: publicUrl,
  },
});

Index.md :
{{{ url }}}

template.html :
{{{ markdown }}}

**Comment by ddezoysa** [comment]
Same issue. Any updates?

**Comment by john-doherty** [comment]
No sorry, super pressed for time at the moment. Please investigate and push a PR if you figure it out 🙏🏽

**Comment by jbreadner** [comment]
I've created a pull request to fix this, as I was having the issue as well.

https://github.com/john-doherty/express-md/pull/5

**Comment by john-doherty** [comment]
Thanks @jbreadner, merged in and pushed `2.1.0` to npm 🙏🏽
